messages:
  no_permission: "You do not have permission to use this command."
  usage: "Usage: /trollity <command> [parameters]"
  player_not_found: "Player not found!"
  burn_success: "The player is on fire!"
  lightning_success: "A lightning struck the player!"
  freeze_success: "The player has been frozen for %seconds% seconds!"
  hunger_success: "The player's hunger has been set to critical!"
  mobs_spawned: "5 mobs have been spawned on the player!"
  blind_success: "The player has been blinded for %seconds% seconds!"
  anvil_success: "An anvil has been dropped on the player's head!"
  hurt_success: "The player's health has been set to critical!"
  kill_success: "The player has been killed, but their inventory is preserved!"
  help_header: "Trollity Command Help"
  help_burn: "/trollity burn <player>: Sets the player on fire for 5 seconds."
  help_lightning: "/trollity lightning <player>: Strikes a lightning bolt on the player."
  help_freeze: "/trollity freeze <player> <sec>: Freezes the player for a specified time."
  help_hunger: "/trollity hunger <player>: Sets the player's hunger to critical."
  help_mobs: "/trollity mobs <player>: Spawns 5 random hostile mobs on the player."
  help_blind: "/trollity blind <player> <sec>: Blind the player for a specified time."
  help_anvil: "/trollity anvil <player>: Drops an anvil on the player from 10 blocks high."
  help_hurt: "/trollity hurt <player>: Reduces the player's health to critical."
  help_kill: "/trollity kill <player>: Kills the player but keeps their inventory."
